global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "product_service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["product-service:8085"]
        labels:
          application: "Product"

  - job_name: "order_service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ "order-service:8081" ]
        labels:
          application: "Order"

  - job_name: "inventory_service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ "inventory-service:8082" ]
        labels:
          application: "Inventory"

  - job_name: "notification_service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ "notification-service:8083" ]
        labels:
          application: "Notification"