version: "3.0"

services:

  api-gateway:
    build:
      context: api-gateway

  discovery-service:
    build:
      context: discovery-server

  inventory-service:
    build:
      context: inventory-service

  notification-service:
    build:
      context: notification-service

  order-service:
    build:
      context: order-service

  product-service:
    build:
      context: product-service

  product-mongodb:
    image: mongo
    ports:
      - "27017:27017"
  order-mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: order-service
  inventory-mysql:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: inventory-service

  keycloak-auth:
    image: quay.io/keycloak/keycloak:26.3.4
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8181:8080"
    command: start-dev
    volumes:
      - keycloak:/opt/keycloak/data/

  zipkin-tracing:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"


  kafka1:
    image: apache/kafka
    container_name: kafka1
    ports:
      - "9092:9092"     # EXTERNAL broker port (Spring Boot access)
      - "19092:19092"   # INTERNAL broker port (Kafka internal communication)
      - "9093:9093"     # CONTROLLER port
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: INTERNAL://kafka1:19092,EXTERNAL://0.0.0.0:9092,CONTROLLER://kafka1:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:19092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:9093,2@kafka2:9094,3@kafka3:9096
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs

  kafka2:
    image: apache/kafka
    container_name: kafka2
    ports:
      - "9095:9095"     # EXTERNAL broker port (Spring Boot access)
      - "19093:19093"   # INTERNAL broker port (Kafka internal communication)
      - "9094:9094"     # CONTROLLER port
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: INTERNAL://kafka2:19093,EXTERNAL://0.0.0.0:9095,CONTROLLER://kafka2:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka2:19093,EXTERNAL://localhost:9095
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:9093,2@kafka2:9094,3@kafka3:9096
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs

  kafka3:
    image: apache/kafka
    container_name: kafka3
    ports:
      - "9097:9097"     # EXTERNAL broker port (Spring Boot access)
      - "19094:19094"   # INTERNAL broker port (Kafka internal communication)
      - "9096:9096"     # CONTROLLER port
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: INTERNAL://kafka3:19094,EXTERNAL://0.0.0.0:9097,CONTROLLER://kafka3:9096
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka3:19094,EXTERNAL://localhost:9097
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:9093,2@kafka2:9094,3@kafka3:9096
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs

volumes:
  keycloak:
