
services:

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: order-service
  mysql2:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: inventory-service

  auth:
    image: quay.io/keycloak/keycloak:26.3.4
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8181:8080"
    command: start-dev

  tracing:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"


